const ROLES = {
  USER: 'user',
  ADMIN: 'admin',              
  USER_ADMIN: 'user_admin',
  FINANCE_ADMIN: 'finance_admin',
  AUDIT_ADMIN: 'audit_admin'
};

const PERMISSIONS = {
  // Wallet permissions
  VIEW_OWN_WALLET: [ROLES.USER, ROLES.FINANCE_ADMIN],
  VIEW_ALL_WALLETS: [ROLES.ADMIN, ROLES.FINANCE_ADMIN],
  MANAGE_WALLETS: [ROLES.ADMIN, ROLES.FINANCE_ADMIN],
  CREATE_WALLET: [ROLES.USER, ROLES.USER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.ADMIN],
  DELETE_WALLET: [ROLES.USER, ROLES.USER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.ADMIN],
  
  // Transaction permissions
  DEPOSIT: [ROLES.USER, ROLES.USER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.ADMIN],
  WITHDRAW: [ROLES.USER, ROLES.USER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.ADMIN],
  TRANSFER: [ROLES.USER, ROLES.USER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.ADMIN],
  VIEW_TRANSACTIONS: [ROLES.USER, ROLES.USER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.AUDIT_ADMIN, ROLES.ADMIN],
  
  // Admin operations
  ACTIVATE_WALLET: [ROLES.ADMIN, ROLES.FINANCE_ADMIN],
  DEACTIVATE_WALLET: [ROLES.ADMIN, ROLES.FINANCE_ADMIN],
  VIEW_USER_WALLETS: [ROLES.ADMIN, ROLES.FINANCE_ADMIN, ROLES.AUDIT_ADMIN],
  VIEW_WALLET_BY_ID: [ROLES.ADMIN, ROLES.FINANCE_ADMIN, ROLES.AUDIT_ADMIN]
};

module.exports = {
  ROLES,
  PERMISSIONS
};