



const CONFIG = {
  SUPPORTED_CURRENCIES: ['USD', 'EUR', 'GBP', 'JPY', 'BTC', 'ETH'],
  MAX_TRANSACTION_AMOUNT: 1000000,
  MIN_TRANSACTION_AMOUNT: 0.01,
  DECIMAL_PLACES: 4,
  TRANSACTION_TIMEOUT: 30000, // 30 seconds
  MAX_DAILY_TRANSACTIONS: 100
};


exports.CONFIG = CONFIG;