name: CI/CD for User Service

on:
  push:
    branches: [main]
    paths:
      - 'services/user-service/**'   # Trigger only on user-service changes

env:
  DOCKER_REPO_PREFIX: mtarmidi
  IMAGE_TAG: latest
  TRIVY_SEVERITY: CRITICAL,HIGH

jobs:
  build:
    name: Build & Push User Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/user-service
          push: false
          tags: ${{ env.DOCKER_REPO_PREFIX }}/user-service:${{ env.IMAGE_TAG }}
          outputs: type=docker,dest=/tmp/user-service.tar

      - name: Load image
        run: docker load -i /tmp/user-service.tar

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_REPO_PREFIX }}/user-service:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1
          severity: ${{ env.TRIVY_SEVERITY }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/user-service
          push: true
          tags: ${{ env.DOCKER_REPO_PREFIX }}/user-service:${{ env.IMAGE_TAG }}
